services:
  - type: web
    name: webminecraft-server
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm run server
    healthCheckPath: /health
    envVars:
      - key: MAX_PLAYERS
        value: "10"
