import * as THREE from "three";
import { createCharacterModel, createCharacterTexture, CHARACTER_TEXTURE_KEY } from "./characterModel.js";
const PALETTE=["#202020","#f4f4f4","#c98d62","#8b5a3c","#f0c7a0","#3974bd","#4b8051","#a94d42","#d1a43c","#303947","#171717","#70472c","#79b5c9","#553e80","#777777","#b9b9b9"];
const css=document.createElement("style");css.textContent=`
#characterEditor{position:fixed;inset:0;z-index:500;display:none;align-items:center;justify-content:center;padding:18px;background:rgba(9,12,15,.9);color:#f5f5f5;font-family:Arial,sans-serif}#characterEditor.open{display:flex}#characterEditor *{box-sizing:border-box}
#characterEditorPanel{width:min(1100px,100%);height:min(740px,94vh);min-height:480px;display:grid;grid-template-columns:minmax(0,1.1fr) minmax(320px,.9fr);overflow:hidden;background:#252525;border:2px solid #777;box-shadow:0 18px 60px #000b}
#characterEditorPreview{position:relative;min-width:0;background:radial-gradient(ellipse at 50% 38%,#555 0,#303030 42%,#181818 100%)}#characterEditorPreview canvas{width:100%;height:100%;display:block}#characterEditorHint{position:absolute;left:14px;bottom:12px;color:#ccc;font-size:11px;letter-spacing:1px;text-transform:uppercase;pointer-events:none}
#characterEditorControls{padding:22px;overflow:auto;background:#292929}#characterEditorTitle{margin:0 0 5px;font-size:24px;letter-spacing:1px}#characterEditorSub{color:#aaa;font-size:12px;margin:0 0 18px}#skinCanvasWrap{width:min(100%,384px);aspect-ratio:1;background:#181818;border:2px solid #777;image-rendering:pixelated;touch-action:none}#skinCanvas{display:block;width:100%;height:100%;image-rendering:pixelated;cursor:crosshair;touch-action:none}
.characterLabel{display:block;margin:17px 0 8px;color:#ddd;font-size:12px;font-weight:700;text-transform:uppercase;letter-spacing:1px}#skinPalette{display:grid;grid-template-columns:repeat(8,minmax(0,1fr));gap:7px}.skinColor{aspect-ratio:1;border:2px solid #111;outline:1px solid #777;cursor:pointer}.skinColor[aria-pressed=true]{outline:3px solid white;outline-offset:2px}
#characterActions{display:flex;gap:8px;margin-top:20px}.characterAction{flex:1;min-height:42px;border:2px solid #111;border-top-color:#aaa;border-left-color:#aaa;background:#666;color:white;font-weight:700;cursor:pointer}#characterSave{background:#668746}#characterClose{position:absolute;top:10px;right:12px;z-index:3;width:40px;height:40px;border:1px solid #888;background:#222;color:#fff;font-size:23px;cursor:pointer}
@media(max-width:700px){#characterEditor{padding:0}#characterEditorPanel{width:100%;height:100%;min-height:0;grid-template-columns:1fr;grid-template-rows:minmax(180px,32vh) 1fr}#characterEditorControls{padding:15px}#characterEditorTitle{font-size:21px}#characterEditorSub{margin-bottom:10px}#skinCanvasWrap{width:min(100%,300px)}.characterLabel{margin-top:13px}}`;
document.head.appendChild(css);
const overlay=document.createElement("section");overlay.id="characterEditor";overlay.setAttribute("aria-label","Character texture editor");overlay.innerHTML=`<div id="characterEditorPanel"><div id="characterEditorPreview"><button id="characterClose" aria-label="Close character editor">×</button><div id="characterEditorHint">Drag to rotate · Live game model</div></div><div id="characterEditorControls"><h2 id="characterEditorTitle">CHARACTER TEXTURE EDITOR</h2><p id="characterEditorSub">Paint pixels on your skin texture. Body shape and parts cannot be changed.</p><span class="characterLabel">64 × 64 skin texture</span><div id="skinCanvasWrap"><canvas id="skinCanvas" width="64" height="64"></canvas></div><span class="characterLabel">Paint color</span><div id="skinPalette"></div><div id="characterActions"><button class="characterAction" id="characterReset">RESET TEXTURE</button><button class="characterAction" id="characterSave">SAVE TEXTURE</button></div></div></div>`;document.body.appendChild(overlay);
const skinCanvas=overlay.querySelector("#skinCanvas"),skinCtx=skinCanvas.getContext("2d",{willReadFrequently:true});skinCtx.imageSmoothingEnabled=false;
const texture=createCharacterTexture(),textureCanvas=texture.userData.canvas,textureCtx=textureCanvas.getContext("2d",{willReadFrequently:true});textureCtx.imageSmoothingEnabled=false;
function copyTextureToEditor(){skinCtx.clearRect(0,0,64,64);skinCtx.drawImage(textureCanvas,0,0);skinCtx.imageSmoothingEnabled=false;}copyTextureToEditor();
let selectedColor=PALETTE[5],painting=false,avatarYaw=-.22;const palette=overlay.querySelector("#skinPalette");
for(const color of PALETTE){const b=document.createElement("button");b.type="button";b.className="skinColor";b.style.background=color;b.title=color;b.setAttribute("aria-label",color);b.setAttribute("aria-pressed",String(color===selectedColor));b.addEventListener("click",()=>{selectedColor=color;for(const el of palette.children)el.setAttribute("aria-pressed",String(el.title===selectedColor));});palette.appendChild(b);}
function paintAt(e){const r=skinCanvas.getBoundingClientRect(),x=Math.max(0,Math.min(63,Math.floor((e.clientX-r.left)/r.width*64))),y=Math.max(0,Math.min(63,Math.floor((e.clientY-r.top)/r.height*64)));skinCtx.fillStyle=selectedColor;skinCtx.fillRect(x,y,1,1);textureCtx.fillStyle=selectedColor;textureCtx.fillRect(x,y,1,1);texture.needsUpdate=true;}
skinCanvas.addEventListener("pointerdown",e=>{painting=true;skinCanvas.setPointerCapture(e.pointerId);paintAt(e);});skinCanvas.addEventListener("pointermove",e=>{if(painting)paintAt(e);});skinCanvas.addEventListener("pointerup",()=>painting=false);skinCanvas.addEventListener("pointercancel",()=>painting=false);
const scene=new THREE.Scene();scene.background=new THREE.Color("#303030");const camera=new THREE.PerspectiveCamera(32,1,.1,80);camera.position.set(3.8,2.7,6.8);camera.lookAt(0,.95,0);const renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,1.5));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;overlay.querySelector("#characterEditorPreview").prepend(renderer.domElement);
scene.add(new THREE.HemisphereLight("#e9f4ff","#6b5946",2));const key=new THREE.DirectionalLight("#fff1d8",2.7);key.position.set(4,8,5);key.castShadow=true;scene.add(key);const rim=new THREE.DirectionalLight("#9bbfff",1.2);rim.position.set(-4,4,-3);scene.add(rim);const avatar=createCharacterModel(texture);scene.add(avatar);const ground=new THREE.Mesh(new THREE.CircleGeometry(2.4,32),new THREE.MeshStandardMaterial({color:"#414141",roughness:1}));ground.rotation.x=-Math.PI/2;ground.position.y=-.02;ground.receiveShadow=true;scene.add(ground);
let dragging=false,lastX=0;const previewCanvas=renderer.domElement;previewCanvas.style.touchAction="pan-y";previewCanvas.addEventListener("pointerdown",e=>{dragging=true;lastX=e.clientX;previewCanvas.setPointerCapture(e.pointerId);});previewCanvas.addEventListener("pointermove",e=>{if(!dragging)return;avatarYaw+=(e.clientX-lastX)*.012;lastX=e.clientX;avatar.rotation.y=avatarYaw;});previewCanvas.addEventListener("pointerup",()=>dragging=false);previewCanvas.addEventListener("pointercancel",()=>dragging=false);
function resize(){const host=overlay.querySelector("#characterEditorPreview"),w=Math.max(1,host.clientWidth),h=Math.max(1,host.clientHeight);renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();}
function show(){overlay.classList.add("open");resize();copyTextureToEditor();}function close(){overlay.classList.remove("open");}
function save(){try{localStorage.setItem(CHARACTER_TEXTURE_KEY,textureCanvas.toDataURL("image/png"));}catch{}window.dispatchEvent(new CustomEvent("webminecraft-character-changed"));const b=overlay.querySelector("#characterSave");b.textContent="SAVED ✓";setTimeout(()=>b.textContent="SAVE TEXTURE",1000);}
function reset(){textureCtx.clearRect(0,0,64,64);textureCtx.fillStyle="#b9b9b9";textureCtx.fillRect(0,0,64,64);textureCtx.fillStyle="#c98d62";textureCtx.fillRect(8,8,8,8);textureCtx.fillStyle="#3974bd";textureCtx.fillRect(20,20,8,12);textureCtx.fillStyle="#c98d62";textureCtx.fillRect(44,20,4,12);textureCtx.fillRect(36,52,4,12);textureCtx.fillStyle="#303947";textureCtx.fillRect(4,20,4,12);textureCtx.fillRect(20,52,4,12);textureCtx.fillStyle="#39291f";textureCtx.fillRect(8,8,8,2);textureCtx.fillRect(8,8,2,8);textureCtx.fillStyle="#263f68";textureCtx.fillRect(10,11,1,1);textureCtx.fillRect(13,11,1,1);texture.needsUpdate=true;copyTextureToEditor();}
overlay.querySelector("#characterClose").addEventListener("click",close);overlay.querySelector("#characterReset").addEventListener("click",reset);overlay.querySelector("#characterSave").addEventListener("click",save);overlay.addEventListener("click",e=>{if(e.target===overlay)close();});window.addEventListener("keydown",e=>{if(e.key==="Escape"&&overlay.classList.contains("open"))close();});window.addEventListener("resize",resize);
function addMenuButton(){const host=document.querySelector("#menuButtons");if(!host||document.querySelector("#characterEditorOpen"))return;const b=document.createElement("button");b.className="menuButton";b.id="characterEditorOpen";b.type="button";b.textContent="CHARACTER TEXTURE";b.addEventListener("click",show);const settings=host.querySelector("#menuSettingsButton");if(settings)host.insertBefore(b,settings);else host.appendChild(b);}addMenuButton();window.addEventListener("DOMContentLoaded",addMenuButton,{once:true});
function render(){requestAnimationFrame(render);if(overlay.classList.contains("open"))renderer.render(scene,camera);}render();
