import * as THREE from "three";
import { getBlockAt, getBlockTypes, CHUNK_SIZE } from "./world.js";
import { waterTexture } from "./blocks.js";

/*
 * Minecraft-style water solver.
 *
 * The important rules mirrored here are:
 * - water ticks on a 5-game-tick cadence;
 * - a source first tries to flow downward;
 * - otherwise flowing water spreads horizontally with level decay;
 * - horizontal spread prefers the shortest reachable drop;
 * - two horizontal source neighbors can create a new source when supported;
 * - falling water is full height and regains normal flow behavior when it lands.
 *
 * Water is kept as a client-side fluid layer instead of pretending it is a
 * normal block ID. Static ocean water generated by world.js is converted into
 * source cells once and its duplicate render mesh is removed.
 */

const SOURCE_LEVEL = 0;
const MAX_FLOW_LEVEL = 7;
const FALLING_LEVEL = 0;
const MIN_Y = -32;
const MAX_Y = 95;

const TICK_MS = 250;
const MAX_CELLS_PER_TICK = 1800;
const MAX_CHUNK_REBUILDS_PER_TICK = 8;
const MAX_WATER_CELLS = 90000;
const DROP_SEARCH_DISTANCE = 4;
const ACTIVE_QUEUE_LIMIT = 120000;
const FLOW_LEVEL_STEP = 1;

const DIRS = [
    [1, 0],
    [-1, 0],
    [0, 1],
    [0, -1]
];

const BLOCK = getBlockTypes();

const water = new Map();
const chunkCells = new Map();
const activeQueue = [];
const activeSet = new Set();
const dirtyChunks = new Set();
const dynamicMeshes = new Map();
const loadedChunkRefs = new Map();
const staticSourceOwners = new WeakMap();
const sourceOwnerCounts = new Map();

let scene = null;
let initialized = false;
let sceneHooksInstalled = false;
let queueHead = 0;
let lastTick = 0;

waterTexture.wrapS = THREE.RepeatWrapping;
waterTexture.wrapT = THREE.ClampToEdgeWrapping;
waterTexture.magFilter = THREE.NearestFilter;
waterTexture.minFilter = THREE.NearestFilter;
waterTexture.colorSpace = THREE.SRGBColorSpace;
waterTexture.needsUpdate = true;

const fluidMaterial = new THREE.MeshPhongMaterial({
    map: waterTexture,
    color: 0xffffff,
    transparent: true,
    opacity: 0.82,
    depthWrite: false,
    depthTest: true,
    side: THREE.DoubleSide,
    shininess: 85,
    specular: 0x8fcfe8,
    emissive: 0x071a22,
    emissiveIntensity: 0.08,
    vertexColors: true
});
fluidMaterial.forceSinglePass = true;

const key = (x, y, z) => `${x},${y},${z}`;
const parseKey = value => value.split(",").map(Number);
const chunkKey = (x, z) => `${Math.floor(x / CHUNK_SIZE)},${Math.floor(z / CHUNK_SIZE)}`;
const floorCoord = value => Math.floor(Number(value));

function enqueue(x, y, z) {
    x = floorCoord(x);
    y = floorCoord(y);
    z = floorCoord(z);

    if (!Number.isFinite(x) || !Number.isFinite(y) || !Number.isFinite(z)) return;
    if (y < MIN_Y || y > MAX_Y) return;

    const k = key(x, y, z);
    if (activeSet.has(k) || activeQueue.length - queueHead >= ACTIVE_QUEUE_LIMIT) return;

    activeSet.add(k);
    activeQueue.push(k);
}

function activateNeighbors(x, y, z) {
    enqueue(x + 1, y, z);
    enqueue(x - 1, y, z);
    enqueue(x, y + 1, z);
    enqueue(x, y - 1, z);
    enqueue(x, y, z + 1);
    enqueue(x, y, z - 1);
}

function compactQueue() {
    if (queueHead < 4096 || queueHead * 2 < activeQueue.length) return;
    activeQueue.splice(0, queueHead);
    queueHead = 0;
}

function markCell(x, z) {
    dirtyChunks.add(chunkKey(x, z));

    const cx = Math.floor(x / CHUNK_SIZE);
    const cz = Math.floor(z / CHUNK_SIZE);

    if (Math.floor((x + 1) / CHUNK_SIZE) !== cx) dirtyChunks.add(chunkKey(x + 1, z));
    if (Math.floor((x - 1) / CHUNK_SIZE) !== cx) dirtyChunks.add(chunkKey(x - 1, z));
    if (Math.floor((z + 1) / CHUNK_SIZE) !== cz) dirtyChunks.add(chunkKey(x, z + 1));
    if (Math.floor((z - 1) / CHUNK_SIZE) !== cz) dirtyChunks.add(chunkKey(x, z - 1));
}

function isLoadedXZ(x, z) {
    return loadedChunkRefs.has(chunkKey(x, z));
}

function isAir(x, y, z) {
    return y >= MIN_Y && y <= MAX_Y && isLoadedXZ(x, z) && getBlockAt(x, y, z) === BLOCK.AIR;
}

function isFluidSpace(x, y, z) {
    return isAir(x, y, z);
}

function getWater(x, y, z) {
    return water.get(key(x, y, z)) || null;
}

function isSource(cell) {
    return !!cell?.source;
}

function isFullWater(cell) {
    return !!cell && (cell.falling || cell.source || cell.level === 0);
}

function fluidHeight(cell) {
    if (!cell) return 0;
    if (cell.falling || cell.source || cell.level === 0) return 1;
    return (MAX_FLOW_LEVEL + 1 - cell.level) / (MAX_FLOW_LEVEL + 1);
}

function state(level = 0, { falling = false, source = false, createdSource = false } = {}) {
    return {
        level: source || falling ? 0 : THREE.MathUtils.clamp(Math.floor(level), 0, MAX_FLOW_LEVEL),
        falling: !!falling,
        source: !!source,
        createdSource: !!createdSource
    };
}

function sameState(a, b) {
    if (!a || !b) return a === b;
    return a.level === b.level &&
        a.falling === b.falling &&
        a.source === b.source &&
        a.createdSource === b.createdSource;
}

function addCell(x, y, z, nextState, activate = true) {
    if (!isFluidSpace(x, y, z)) return false;

    const k = key(x, y, z);
    const current = water.get(k);

    if (current) {
        const merged = {
            ...current,
            ...nextState,
            createdSource: current.createdSource || !!nextState.createdSource
        };
        if (current.source) {
            merged.source = true;
            merged.falling = false;
            merged.level = 0;
        }
        if (sameState(current, merged)) return false;
        water.set(k, merged);
    } else {
        if (water.size >= MAX_WATER_CELLS) return false;
        water.set(k, { ...nextState });

        let cells = chunkCells.get(chunkKey(x, z));
        if (!cells) {
            cells = new Set();
            chunkCells.set(chunkKey(x, z), cells);
        }
        cells.add(k);
    }

    if (activate) activateNeighbors(x, y, z);
    enqueue(x, y, z);
    markCell(x, z);
    return true;
}

function removeCell(x, y, z) {
    const k = key(floorCoord(x), floorCoord(y), floorCoord(z));
    const current = water.get(k);
    if (!current || current.source || sourceOwnerCounts.has(k)) return false;

    water.delete(k);

    const [cx, cy, cz] = parseKey(k);
    const cells = chunkCells.get(chunkKey(cx, cz));
    if (cells) {
        cells.delete(k);
        if (!cells.size) chunkCells.delete(chunkKey(cx, cz));
    }

    enqueue(cx, cy, cz);
    activateNeighbors(cx, cy, cz);
    markCell(cx, cz);
    return true;
}

function setCellRaw(x, y, z, nextState) {
    const k = key(x, y, z);
    const previous = water.get(k);

    if (!nextState) {
        if (!previous || previous.source || sourceOwnerCounts.has(k)) return false;
        water.delete(k);
        const cells = chunkCells.get(chunkKey(x, z));
        if (cells) {
            cells.delete(k);
            if (!cells.size) chunkCells.delete(chunkKey(x, z));
        }
        markCell(x, z);
        return true;
    }

    if (previous && sameState(previous, nextState)) return false;

    if (!previous) {
        if (water.size >= MAX_WATER_CELLS) return false;
        water.set(k, { ...nextState });

        let cells = chunkCells.get(chunkKey(x, z));
        if (!cells) {
            cells = new Set();
            chunkCells.set(chunkKey(x, z), cells);
        }
        cells.add(k);
    } else {
        const merged = { ...previous, ...nextState };
        if (previous.source) {
            merged.source = true;
            merged.falling = false;
            merged.level = 0;
        }
        merged.createdSource = previous.createdSource || !!nextState.createdSource;
        water.set(k, merged);
    }

    enqueue(x, y, z);
    activateNeighbors(x, y, z);
    markCell(x, z);
    return true;
}

function registerChunkRef(object) {
    if (!object?.userData?.isChunk || object.userData?.isDynamicWater) return null;
    if (object.userData.waterPhysicsChunkRegistered) return object.userData.waterPhysicsChunkKey || null;

    const geometry = object.geometry;
    if (!geometry) return null;
    if (!geometry.boundingBox) geometry.computeBoundingBox();
    if (!geometry.boundingBox) return null;

    const centerX = (geometry.boundingBox.min.x + geometry.boundingBox.max.x) * 0.5;
    const centerZ = (geometry.boundingBox.min.z + geometry.boundingBox.max.z) * 0.5;
    const ck = `${Math.floor(centerX / CHUNK_SIZE)},${Math.floor(centerZ / CHUNK_SIZE)}`;

    loadedChunkRefs.set(ck, (loadedChunkRefs.get(ck) || 0) + 1);
    object.userData.waterPhysicsChunkRegistered = true;
    object.userData.waterPhysicsChunkKey = ck;
    return ck;
}

function pruneUnloadedChunk(ck) {
    const cells = chunkCells.get(ck);
    if (!cells?.size) return;

    const boundary = [];

    for (const k of cells) {
        const [x, y, z] = parseKey(k);
        const lx = ((x % CHUNK_SIZE) + CHUNK_SIZE) % CHUNK_SIZE;
        const lz = ((z % CHUNK_SIZE) + CHUNK_SIZE) % CHUNK_SIZE;

        if (lx === 0 || lx === CHUNK_SIZE - 1 || lz === 0 || lz === CHUNK_SIZE - 1) {
            boundary.push([x, y, z]);
        }

        sourceOwnerCounts.delete(k);
        water.delete(k);
    }

    chunkCells.delete(ck);

    for (const [x, y, z] of boundary) {
        activateNeighbors(x, y, z);
        markCell(x, z);
    }
}

function unregisterChunkRef(ck) {
    if (!ck) return;

    const next = (loadedChunkRefs.get(ck) || 1) - 1;
    if (next <= 0) {
        loadedChunkRefs.delete(ck);
        pruneUnloadedChunk(ck);
    } else {
        loadedChunkRefs.set(ck, next);
    }
}

function addSourceOwner(k) {
    const count = (sourceOwnerCounts.get(k) || 0) + 1;
    sourceOwnerCounts.set(k, count);
    return count;
}

function removeSourceOwner(k) {
    const count = (sourceOwnerCounts.get(k) || 0) - 1;

    if (count > 0) {
        sourceOwnerCounts.set(k, count);
        return;
    }

    sourceOwnerCounts.delete(k);

    const cell = water.get(k);
    if (!cell) return;

    if (cell.createdSource) {
        enqueue(...parseKey(k));
        return;
    }

    water.delete(k);

    const [x, y, z] = parseKey(k);
    const cells = chunkCells.get(chunkKey(x, z));
    if (cells) {
        cells.delete(k);
        if (!cells.size) chunkCells.delete(chunkKey(x, z));
    }

    enqueue(x, y, z);
    activateNeighbors(x, y, z);
    markCell(x, z);
}

function registerWaterMesh(mesh) {
    if (!mesh || mesh.userData?.isDynamicWater || mesh.userData?.waterPhysicsRegistered) return;
    if (mesh.userData?.isWater !== true && !mesh.name?.toLowerCase().includes("water")) return;

    const position = mesh.geometry?.getAttribute("position");
    if (!position) return;

    mesh.userData.waterPhysicsRegistered = true;

    const owned = new Set();
    staticSourceOwners.set(mesh, owned);

    for (let i = 0; i < position.count; i += 4) {
        const x = Math.round(position.getX(i) + (mesh.position?.x || 0));
        const y = Math.round(position.getY(i) + (mesh.position?.y || 0));
        const z = Math.round(position.getZ(i) + (mesh.position?.z || 0));

        if (!Number.isFinite(x) || !Number.isFinite(y) || !Number.isFinite(z)) continue;

        const k = key(x, y, z);
        if (owned.has(k)) continue;

        owned.add(k);
        addSourceOwner(k);

        const current = water.get(k);
        if (current) {
            current.level = 0;
            current.falling = false;
            current.source = true;
            current.createdSource = false;
            enqueue(x, y, z);
            activateNeighbors(x, y, z);
            markCell(x, z);
        } else if (isFluidSpace(x, y, z)) {
            water.set(k, state(0, { source: true }));
            let cells = chunkCells.get(chunkKey(x, z));
            if (!cells) {
                cells = new Set();
                chunkCells.set(chunkKey(x, z), cells);
            }
            cells.add(k);
            enqueue(x, y, z);
            activateNeighbors(x, y, z);
            markCell(x, z);
        }
    }

    // world.js already generated a water mesh for this cell set. The fluid
    // solver owns the actual render now, so remove the duplicate geometry.
    mesh.userData.isDynamicWater = true;
    if (mesh.parent) mesh.parent.remove(mesh);
    mesh.geometry?.dispose?.();
    if (Array.isArray(mesh.material)) {
        for (const material of mesh.material) material.dispose?.();
    } else {
        mesh.material?.dispose?.();
    }
}

function unregisterWaterMesh(mesh) {
    const owned = staticSourceOwners.get(mesh);
    if (!owned) return;

    for (const k of owned) removeSourceOwner(k);
    staticSourceOwners.delete(mesh);
}

function registerObject(object) {
    if (!object || object.userData?.isDynamicWater) return;

    if (object.userData?.isWater === true || object.name?.toLowerCase().includes("water")) {
        registerWaterMesh(object);
        return;
    }

    registerChunkRef(object);
}

function unregisterObject(object) {
    if (!object || object.userData?.isDynamicWater) return;

    if (object.userData?.waterPhysicsChunkRegistered) {
        unregisterChunkRef(object.userData.waterPhysicsChunkKey);
        delete object.userData.waterPhysicsChunkRegistered;
        delete object.userData.waterPhysicsChunkKey;
    }

    unregisterWaterMesh(object);
}

function installSceneHooks() {
    if (sceneHooksInstalled) return;
    sceneHooksInstalled = true;

    const previousAdd = THREE.Scene.prototype.add;
    THREE.Scene.prototype.add = function (...objects) {
        const result = previousAdd.apply(this, objects);
        for (const object of objects) {
            object?.traverse ? object.traverse(registerObject) : registerObject(object);
        }
        return result;
    };

    const previousRemove = THREE.Scene.prototype.remove;
    THREE.Scene.prototype.remove = function (...objects) {
        const result = previousRemove.apply(this, objects);
        for (const object of objects) {
            object?.traverse ? object.traverse(unregisterObject) : unregisterObject(object);
        }
        return result;
    };
}

function clearFluidState() {
    for (const mesh of dynamicMeshes.values()) {
        if (mesh.parent) mesh.parent.remove(mesh);
        mesh.geometry?.dispose?.();
    }

    dynamicMeshes.clear();
    water.clear();
    chunkCells.clear();
    activeQueue.length = 0;
    activeSet.clear();
    dirtyChunks.clear();
    sourceOwnerCounts.clear();
    loadedChunkRefs.clear();
    queueHead = 0;
}

function scanSceneObjects() {
    if (scene) scene.traverse(registerObject);
}

function countAdjacentSources(x, y, z) {
    let count = 0;

    for (const [dx, dz] of DIRS) {
        if (isSource(getWater(x + dx, y, z + dz))) count++;
    }

    return count;
}

function canCreateSource(x, y, z) {
    if (!isFluidSpace(x, y, z)) return false;
    if (getWater(x, y, z)) return false;

    const belowAir = isAir(x, y - 1, z);
    const belowSource = isSource(getWater(x, y - 1, z));

    // Java's source conversion requires the target to have solid support or
    // a water source directly underneath.
    if (belowAir && !belowSource) return false;
    return countAdjacentSources(x, y, z) >= 2;
}

function strongestNeighborLevel(x, y, z) {
    let best = Infinity;

    for (const [dx, dz] of DIRS) {
        const neighbor = getWater(x + dx, y, z + dz);
        if (!neighbor) continue;

        if (neighbor.source || neighbor.falling || neighbor.level === 0) {
            best = Math.min(best, 0);
        } else {
            best = Math.min(best, neighbor.level);
        }
    }

    return Number.isFinite(best) ? best : null;
}

function hasOpenBelow(x, y, z) {
    return isAir(x, y - 1, z);
}

function findShortestDrop(x, y, z) {
    if (!isFluidSpace(x, y, z)) return Infinity;

    if (hasOpenBelow(x, y, z)) return 0;

    const visited = new Set([key(x, y, z)]);
    const frontier = [[x, z, 0]];

    while (frontier.length) {
        const [cx, cz, distance] = frontier.shift();
        if (distance >= DROP_SEARCH_DISTANCE) continue;

        for (const [dx, dz] of DIRS) {
            const nx = cx + dx;
            const nz = cz + dz;
            const k = key(nx, y, nz);

            if (visited.has(k)) continue;
            if (!isFluidSpace(nx, y, nz)) continue;

            visited.add(k);

            if (hasOpenBelow(nx, y, nz)) return distance + 1;
            frontier.push([nx, nz, distance + 1]);
        }
    }

    return Infinity;
}

function horizontalTargets(x, y, z) {
    const candidates = [];

    for (const [dx, dz] of DIRS) {
        const nx = x + dx;
        const nz = z + dz;

        if (!isFluidSpace(nx, y, nz)) continue;

        candidates.push({
            x: nx,
            z: nz,
            distance: findShortestDrop(nx, y, nz)
        });
    }

    if (!candidates.length) return [];

    let bestDistance = Infinity;
    for (const candidate of candidates) {
        if (candidate.distance < bestDistance) bestDistance = candidate.distance;
    }

    if (!Number.isFinite(bestDistance)) return candidates;
    return candidates.filter(candidate => candidate.distance === bestDistance);
}

function sourceNeighborsForCell(x, y, z) {
    const sources = [];
    for (const [dx, dz] of DIRS) {
        if (isSource(getWater(x + dx, y, z + dz))) {
            sources.push([dx, dz]);
        }
    }
    return sources;
}

function setCellFromNeighbor(x, y, z) {
    const source = canCreateSource(x, y, z);
    if (source) return state(0, { source: true, createdSource: true });

    const strongest = strongestNeighborLevel(x, y, z);
    if (strongest == null) return null;

    const nextLevel = strongest + FLOW_LEVEL_STEP;
    if (nextLevel > MAX_FLOW_LEVEL) return null;

    return state(nextLevel);
}

function removeOrKeepCurrent(k, current) {
    if (!current) return;

    if (current.source || sourceOwnerCounts.has(k)) {
        current.source = true;
        current.falling = false;
        current.level = 0;
        enqueue(...parseKey(k));
        return;
    }

    if (current.createdSource) {
        enqueue(...parseKey(k));
        return;
    }

    setCellRaw(...parseKey(k), null);
}

function evaluateCell(x, y, z, proposals) {
    const k = key(x, y, z);
    const current = water.get(k);

    if (!isLoadedXZ(x, z)) {
        if (current && !current.source && !sourceOwnerCounts.has(k)) {
            proposals.set(k, null);
        }
        return;
    }

    if (!isAir(x, y, z)) {
        if (current && !current.source && !sourceOwnerCounts.has(k)) {
            proposals.set(k, null);
        }
        return;
    }

    if (!current) {
        if (sourceOwnerCounts.has(k)) {
            proposals.set(k, state(0, { source: true }));
            return;
        }

        const generatedSource = canCreateSource(x, y, z);
        if (generatedSource) {
            proposals.set(k, state(0, { source: true, createdSource: true }));
            return;
        }

        if (hasOpenBelow(x, y + 1, z) && isFullWater(getWater(x, y + 1, z))) {
            proposals.set(k, state(FALLING_LEVEL, { falling: true }));
            return;
        }

        const fromNeighbors = setCellFromNeighbor(x, y, z);
        if (fromNeighbors) proposals.set(k, fromNeighbors);
        return;
    }

    if (current.source || sourceOwnerCounts.has(k)) {
        current.source = true;
        current.falling = false;
        current.level = 0;

        if (hasOpenBelow(x, y, z) && !getWater(x, y - 1, z)) {
            proposals.set(k, state(0, { source: true }));
            proposals.set(key(x, y - 1, z), state(0, { falling: true }));
            return;
        }

        for (const target of horizontalTargets(x, y, z)) {
            const targetKey = key(target.x, y, target.z);
            if (!water.has(targetKey)) proposals.set(targetKey, state(1));
        }

        proposals.set(k, state(0, { source: true }));
        return;
    }

    if (current.falling) {
        if (hasOpenBelow(x, y, z) && !getWater(x, y - 1, z)) {
            proposals.set(k, state(0, { falling: true }));
            proposals.set(key(x, y - 1, z), state(0, { falling: true }));
            return;
        }

        const landed = setCellFromNeighbor(x, y, z) || state(0);
        proposals.set(k, landed);
        return;
    }

    if (hasOpenBelow(x, y, z) && !getWater(x, y - 1, z)) {
        proposals.set(k, state(0, { falling: true }));
        proposals.set(key(x, y - 1, z), state(0, { falling: true }));
        return;
    }

    const desired = setCellFromNeighbor(x, y, z);

    if (!desired) {
        if (current.createdSource) {
            proposals.set(k, state(0, { source: true, createdSource: true }));
        } else {
            proposals.set(k, null);
        }
        return;
    }

    if (current.createdSource) {
        proposals.set(k, state(0, { source: true, createdSource: true }));
        return;
    }

    proposals.set(k, desired);

    if (desired.level < MAX_FLOW_LEVEL) {
        for (const target of horizontalTargets(x, y, z)) {
            const targetKey = key(target.x, y, target.z);
            if (!water.has(targetKey)) {
                proposals.set(targetKey, state(desired.level + FLOW_LEVEL_STEP));
            }
        }
    }
}

function proposalStrength(nextState) {
    if (!nextState) return -1;
    if (nextState.source) return 1000;
    if (nextState.falling) return 900;
    return MAX_FLOW_LEVEL + 1 - nextState.level;
}

function propose(proposals, k, nextState) {
    const current = proposals.get(k);
    if (current === undefined || proposalStrength(nextState) > proposalStrength(current)) {
        proposals.set(k, nextState);
    }
}

function runFluidTick() {
    let processed = 0;
    const proposals = new Map();

    while (processed < MAX_CELLS_PER_TICK && queueHead < activeQueue.length) {
        const k = activeQueue[queueHead++];
        activeSet.delete(k);

        const [x, y, z] = parseKey(k);
        evaluateCell(x, y, z, proposals);
        processed++;
    }

    for (const [k, nextState] of proposals) {
        const [x, y, z] = parseKey(k);
        propose(proposals, k, nextState);
    }

    for (const [k, nextState] of proposals) {
        const [x, y, z] = parseKey(k);
        const current = water.get(k);

        if (!nextState) {
            if (current && !current.source && !sourceOwnerCounts.has(k)) {
                setCellRaw(x, y, z, null);
            }
            continue;
        }

        if (!current) {
            addCell(x, y, z, nextState, false);
            continue;
        }

        const merged = { ...current, ...nextState };
        if (current.source || sourceOwnerCounts.has(k)) {
            merged.source = true;
            merged.falling = false;
            merged.level = 0;
        }
        if (current.createdSource) {
            merged.createdSource = true;
        }

        if (!sameState(current, merged)) {
            water.set(k, merged);
            enqueue(x, y, z);
            activateNeighbors(x, y, z);
            markCell(x, z);
        }
    }

    compactQueue();
}

function cornerHeight(x, y, z, cx, cz, fallback) {
    const xs = cx > 0 ? [0, 1] : [-1, 0];
    const zs = cz > 0 ? [0, 1] : [-1, 0];
    const samples = [];

    for (const ox of xs) {
        for (const oz of zs) {
            const cell = getWater(x + ox, y, z + oz);
            if (cell) samples.push(fluidHeight(cell));
        }
    }

    if (!samples.length) return fallback;
    return samples.reduce((sum, value) => sum + value, 0) / samples.length;
}

function flowVector(x, y, z) {
    const center = getWater(x, y, z);
    if (!center || center.source || center.falling) return { x: 0, z: 0 };

    const h = fluidHeight(center);
    let vx = 0;
    let vz = 0;

    for (const [dx, dz] of DIRS) {
        const neighbor = fluidHeight(getWater(x + dx, y, z + dz));
        const delta = h - neighbor;
        vx += dx * delta;
        vz += dz * delta;
    }

    const length = Math.hypot(vx, vz);
    if (length < 0.0001) return { x: 0, z: 0 };
    return { x: vx / length, z: vz / length };
}

function uvPoints(angle) {
    const radius = 0.34;
    const cos = Math.cos(angle);
    const sin = Math.sin(angle);

    return [
        [-1, -1],
        [1, -1],
        [1, 1],
        [-1, 1]
    ].map(([u, v]) => [
        0.5 + (u * cos - v * sin) * radius,
        0.5 + (u * sin + v * cos) * radius
    ]);
}

function pushQuad(positions, normals, uvs, colors, indices, points, normal, uv, shade, vertex) {
    for (const point of points) positions.push(...point);
    for (let i = 0; i < 4; i++) {
        normals.push(...normal);
        colors.push(shade, shade, shade);
    }
    for (const point of uv) uvs.push(...point);
    indices.push(vertex, vertex + 1, vertex + 2, vertex, vertex + 2, vertex + 3);
    return vertex + 4;
}

function disposeDynamicMesh(mesh) {
    if (!mesh) return;
    if (mesh.parent) mesh.parent.remove(mesh);
    mesh.geometry?.dispose?.();
}

function buildChunk(ck) {
    if (!scene || !loadedChunkRefs.has(ck)) return;

    const old = dynamicMeshes.get(ck);
    if (old) {
        if (old.parent) old.parent.remove(old);
        old.geometry?.dispose?.();
        dynamicMeshes.delete(ck);
    }

    const cells = chunkCells.get(ck);
    if (!cells?.size) return;

    const positions = [];
    const normals = [];
    const uvs = [];
    const colors = [];
    const indices = [];

    let vertex = 0;

    for (const k of cells) {
        const cell = water.get(k);
        if (!cell) continue;

        const [x, y, z] = parseKey(k);
        const h = fluidHeight(cell);
        const baseY = y - 0.5;
        const topY = baseY + h;

        const above = getWater(x, y + 1, z);
        if (!above && isAir(x, y + 1, z)) {
            const flow = flowVector(x, y, z);

            const topPoints = [
                [x - 0.5, baseY + cornerHeight(x, y, z, -1, -1, h), z - 0.5],
                [x + 0.5, baseY + cornerHeight(x, y, z, 1, -1, h), z - 0.5],
                [x + 0.5, baseY + cornerHeight(x, y, z, 1, 1, h), z + 0.5],
                [x - 0.5, baseY + cornerHeight(x, y, z, -1, 1, h), z + 0.5]
            ];

            vertex = pushQuad(
                positions,
                normals,
                uvs,
                colors,
                indices,
                topPoints,
                [0, 1, 0],
                uvPoints(Math.atan2(flow.z, flow.x)),
                0.96,
                vertex
            );
        }

        for (const [dx, dz] of DIRS) {
            const nx = x + dx;
            const nz = z + dz;

            if (!isFluidSpace(nx, y, nz)) continue;

            const neighbor = getWater(nx, y, nz);
            if (neighbor && fluidHeight(neighbor) >= h - 0.0001) continue;

            const sideTop = baseY + fluidHeight(neighbor);
            let points;
            let normal;

            if (dx === 1) {
                points = [
                    [x + 0.5, baseY, z - 0.5],
                    [x + 0.5, topY, z - 0.5],
                    [x + 0.5, sideTop, z + 0.5],
                    [x + 0.5, baseY, z + 0.5]
                ];
                normal = [1, 0, 0];
            } else if (dx === -1) {
                points = [
                    [x - 0.5, baseY, z + 0.5],
                    [x - 0.5, topY, z + 0.5],
                    [x - 0.5, sideTop, z - 0.5],
                    [x - 0.5, baseY, z - 0.5]
                ];
                normal = [-1, 0, 0];
            } else if (dz === 1) {
                points = [
                    [x + 0.5, baseY, z + 0.5],
                    [x + 0.5, topY, z + 0.5],
                    [x - 0.5, sideTop, z + 0.5],
                    [x - 0.5, baseY, z + 0.5]
                ];
                normal = [0, 0, 1];
            } else {
                points = [
                    [x - 0.5, baseY, z - 0.5],
                    [x - 0.5, topY, z - 0.5],
                    [x + 0.5, sideTop, z - 0.5],
                    [x + 0.5, baseY, z - 0.5]
                ];
                normal = [0, 0, -1];
            }

            vertex = pushQuad(
                positions,
                normals,
                uvs,
                colors,
                indices,
                points,
                normal,
                [[0, 0], [0, h], [1, h], [1, 0]],
                0.84,
                vertex
            );
        }
    }

    if (!positions.length) return;

    const geometry = new THREE.BufferGeometry();
    geometry.setAttribute("position", new THREE.Float32BufferAttribute(positions, 3));
    geometry.setAttribute("normal", new THREE.Float32BufferAttribute(normals, 3));
    geometry.setAttribute("uv", new THREE.Float32BufferAttribute(uvs, 2));
    geometry.setAttribute("color", new THREE.Float32BufferAttribute(colors, 3));
    geometry.setIndex(indices);
    geometry.computeBoundingBox();
    geometry.computeBoundingSphere();

    const mesh = new THREE.Mesh(geometry, fluidMaterial);
    mesh.userData.isDynamicWater = true;
    mesh.userData.isWater = true;
    mesh.userData.waterChunk = ck;
    mesh.frustumCulled = true;

    dynamicMeshes.set(ck, mesh);
    scene.add(mesh);
}

function rebuildDirtyChunks(limit = MAX_CHUNK_REBUILDS_PER_TICK) {
    let rebuilt = 0;

    for (const ck of dirtyChunks) {
        dirtyChunks.delete(ck);
        buildChunk(ck);

        rebuilt++;
        if (rebuilt >= limit) break;
    }
}

function resetForWorld() {
    clearFluidState();
    initialized = true;
    lastTick = performance.now();
}

export function setupWaterPhysics(sceneRef) {
    if (!sceneRef) return;

    scene = sceneRef;
    resetForWorld();
    installSceneHooks();
    scanSceneObjects();

    for (const [k, cell] of water) {
        if (cell.source) enqueue(...parseKey(k));
    }

    while (dirtyChunks.size) rebuildDirtyChunks(64);
}

export function notifyWaterBlockChanged(x, y, z, type = BLOCK.AIR) {
    if (!initialized) return;

    x = floorCoord(x);
    y = floorCoord(y);
    z = floorCoord(z);

    if (![x, y, z].every(Number.isFinite)) return;
    if (y < MIN_Y || y > MAX_Y) return;

    const k = key(x, y, z);
    if (type !== BLOCK.AIR && water.has(k) && !sourceOwnerCounts.has(k)) {
        const cell = water.get(k);
        if (cell && !cell.source) {
            setCellRaw(x, y, z, null);
        }
    }

    enqueue(x, y, z);
    activateNeighbors(x, y, z);
    markCell(x, z);
}

export function updateWaterPhysics() {
    if (!initialized || !scene) return;

    const now = performance.now();
    if (now - lastTick >= TICK_MS) {
        lastTick = now;
        runFluidTick();
    }

    rebuildDirtyChunks();
}

if (typeof window !== "undefined") {
    window.addEventListener("webminecraft:blockchange", event => {
        const detail = event.detail || {};
        if (!Number.isFinite(detail.x) || !Number.isFinite(detail.y) || !Number.isFinite(detail.z)) return;
        notifyWaterBlockChanged(detail.x, detail.y, detail.z, detail.type ?? BLOCK.AIR);
    });

    const loop = () => {
        updateWaterPhysics();
        window.setTimeout(loop, 50);
    };

    window.setTimeout(loop, 50);
}
